import updateElectronApp from 'update-electron-app'
import { app, BrowserWindow, ipcMain, session, shell, nativeTheme, dialog } from 'electron';
import { debug } from './utils';
import * as fs from 'fs';
import * as path from 'path';
import { validateSession, validateFileSize, validateJSONParse, sanitizeSessionData } from './validation';
// import updateElectronApp from 'update-electron-app'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

const onReady = (): void => {
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
        callback({
            responseHeaders: {
                ...details.responseHeaders,
                //   'Content-Security-Policy': ['default-src \'none\'']
                'Content-Security-Policy': ['*'], // 为了支持代理
            },
        });
    });

    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 1000,
        width: 1400,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    if (process.env.NODE_ENV === 'development') {
        mainWindow.webContents.openDevTools();
    }

    mainWindow.webContents.setWindowOpenHandler((details) => {
        if (details.url.startsWith('http')) {
            shell.openExternal(details.url)
            return { action: 'deny' }
        }
        return { action: 'allow' }
    })

    nativeTheme.on('updated', () => {
        mainWindow.webContents.send('native-theme-updated');
    });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', onReady);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        onReady();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

import Store from 'electron-store';
const store = new Store();
ipcMain.handle('getStoreValue', (event, key) => {
    return store.get(key);
});
ipcMain.handle('setStoreValue', (event, key, data) => {
    return store.set(key, data);
});
debug('store path', store.path);

ipcMain.handle('getVersion', () => {
    return app.getVersion();
});
ipcMain.handle('openLink', (event, link) => {
    return shell.openExternal(link);
});

updateElectronApp({
    repo: 'Bin-Huang/chatbox',
    updateInterval: '5 minutes',
})
// theme

ipcMain.handle('shouldUseDarkColors', () => nativeTheme.shouldUseDarkColors);

ipcMain.handle('exportSession', async (event, sessionData) => {
    try {
        const suggestedName = `${sessionData.name.replace(/[^a-z0-9]/gi, '_')}.json`;

        const result = await dialog.showSaveDialog({
            title: 'Export Session',
            defaultPath: path.join(app.getPath('documents'), suggestedName),
            buttonLabel: 'Export',
            filters: [
                { name: 'JSON Files', extensions: ['json'] },
                { name: 'All Files', extensions: ['*'] }
            ]
        });

        if (result.canceled || !result.filePath) {
            return { success: false, cancelled: true };
        }

        const exportData = {
            id: sessionData.id,
            name: sessionData.name,
            messages: sessionData.messages.map((msg: any) => ({
                id: msg.id,
                role: msg.role,
                content: msg.content
            }))
        };

        await fs.promises.writeFile(
            result.filePath,
            JSON.stringify(exportData, null, 2),
            'utf-8'
        );

        return { success: true, filePath: result.filePath };
    } catch (error: any) {
        return { success: false, error: error.message };
    }
});

ipcMain.handle('importSession', async () => {
    try {
        const result = await dialog.showOpenDialog({
            title: 'Import Session',
            buttonLabel: 'Import',
            filters: [
                { name: 'JSON Files', extensions: ['json'] },
                { name: 'All Files', extensions: ['*'] }
            ],
            properties: ['openFile']
        });

        if (result.canceled || !result.filePaths[0]) {
            return { success: false, cancelled: true };
        }

        const filePath = result.filePaths[0];

        const stats = await fs.promises.stat(filePath);
        const sizeValidation = validateFileSize(stats.size);
        if (!sizeValidation.isValid) {
            return { success: false, error: sizeValidation.error };
        }

        const fileContent = await fs.promises.readFile(filePath, 'utf-8');

        const parseResult = validateJSONParse(fileContent);
        if (parseResult.error) {
            return { success: false, error: parseResult.error };
        }

        const validationResult = validateSession(parseResult.data);
        if (!validationResult.isValid) {
            return { success: false, error: validationResult.error };
        }

        const sanitizedData = sanitizeSessionData(parseResult.data);

        return {
            success: true,
            sessionData: sanitizedData,
            warnings: validationResult.warnings
        };
    } catch (error: any) {
        if (error.code === 'ENOENT') {
            return { success: false, error: 'File not found. Please select a valid file.' };
        }
        if (error.code === 'EACCES') {
            return { success: false, error: 'Permission denied. Cannot read the selected file.' };
        }
        if (error.code === 'EISDIR') {
            return { success: false, error: 'Selected path is a directory. Please select a JSON file.' };
        }

        return { success: false, error: `Import failed: ${error.message}` };
    }
});

// updateElectronApp()
